name: 'klaviyo_source_custom'
profile: 'databricks' 
version: '0.9.0'
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

vars:
  klaviyo_source:
    klaviyo_database: 0006_wonsulting
    klaviyo_schema: klaviyo_raw
    klaviyo__event_pass_through_columns: []
    klaviyo__person_pass_through_columns: []

  dbt_utils_dispatch_list: ['spark_utils', 'dbt_utils']
  fivetran_utils_dispatch_list: ['spark_utils']

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

model-paths: ["models"]
packages-install-path: "dbt_packages"

models:
  +materialized: table
  +schema: stg_klaviyo
  klaviyo_source_custom:
    +schema: stg_klaviyo
  klaviyo_source:  # Disable original Fivetran package
    +enabled: false